# thanks to jsk-ros-pkg
# vim:set ts=2 sw=2 et:
language: cpp
compiler:
  - gcc
  #- clang
env:
  global:
    - ROS_DISTRO=hydro # wait until travis will update to 14.04
  matrix:
    - MAVLINK_DIALECT=common
    - MAVLINK_DIALECT=ardupilotmega
    - MAVLINK_DIALECT=paparazzi

before_install:
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  #- sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - sudo sh -c 'echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin ros-$ROS_DISTRO-ros python-rosinstall python-catkin-tools
  # Setup rosdep
  - sudo rosdep init
  - rosdep update

install:
  # Create workspace
  - mkdir -p ~/ros/ws_$REPOSITORY_NAME
  - cd ~/ros/ws_$REPOSITORY_NAME
  - catkin config --init --mkdirs
  - cd src
  # Clone mavlink dependency
  - git clone https://github.com/mavlink/mavlink-gbp-release.git mavlink -b release/jade/mavlink
  # Link the repo we are testing to the new workspace
  - ln -s $CI_SOURCE_PATH .
  # Install dependencies for source repos
  - rosdep install -r -n --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y

before_script:
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - rospack profile

script:
  - cd ~/ros/ws_$REPOSITORY_NAME
  - catkin config --install --cmake-args -DMAVLINK_DIALECT=$MAVLINK_DIALECT
  - catkin build -j4 --verbose --summary
  - catkin run_tests -p1 -j4 --summary
  #- catkin_test_results --all ~/ros/ws_$REPOSITORY_NAME/build

after_failure:
  - find ~/ros/ws_$REPOSITORY_NAME/build -path '*/test_results/*' -type f -exec echo "==== {} ====" \; -exec cat {} \;

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b856f174ff9736ad23ec
    on_success: change
    on_failure: always
    on_start: false
